---
on:
  push:
    paths:
      - 'mkwutil/**'
  pull_request:
    paths:
      - 'mkwutil/**'
name: Test
jobs:
  test:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: requirements.txt

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - run: pip install -r requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'

      - name: Install mkwutil in editable mode
        run: pip install -e .

      - name: Install deps
        run: |
          wget https://github.com/radareorg/radare2/releases/download/5.7.0/radare2-5.7.0-w64.zip
          Expand-Archive -Path radare2-5.7.0-w64.zip -Dest $HOME/radare2

      - name: Run tests
        run: pytest -vv
        env:
          PATH: "$HOME/radare2/bin"
